/*
 * This file was automatically generated by EvoSuite
 * Thu May 04 15:56:12 GMT 2023
 */

package org.example.Main;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.example.Main.NewMenu;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class NewMenu_ESTest extends NewMenu_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      NewMenu newMenu0 = new NewMenu();
      NewMenu.PreCondition newMenu_PreCondition0 = mock(NewMenu.PreCondition.class, new ViolatedAssumptionAnswer());
      // Undeclared exception!
      try { 
        newMenu0.setPreCondition(2463, newMenu_PreCondition0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.example.Main.NewMenu", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      String[] stringArray0 = new String[8];
      NewMenu newMenu0 = new NewMenu(stringArray0);
      NewMenu.PreCondition newMenu_PreCondition0 = mock(NewMenu.PreCondition.class, new ViolatedAssumptionAnswer());
      // Undeclared exception!
      try { 
        newMenu0.setPreCondition(923, newMenu_PreCondition0);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Index: 922, Size: 8
         //
         verifyException("java.util.ArrayList", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      NewMenu newMenu0 = new NewMenu();
      NewMenu.Handler newMenu_Handler0 = mock(NewMenu.Handler.class, new ViolatedAssumptionAnswer());
      // Undeclared exception!
      try { 
        newMenu0.setHandler((-1141), newMenu_Handler0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.example.Main.NewMenu", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      String[] stringArray0 = new String[1];
      NewMenu newMenu0 = new NewMenu(stringArray0);
      NewMenu.Handler newMenu_Handler0 = mock(NewMenu.Handler.class, new ViolatedAssumptionAnswer());
      // Undeclared exception!
      try { 
        newMenu0.setHandler(2117, newMenu_Handler0);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Index: 2116, Size: 1
         //
         verifyException("java.util.ArrayList", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      String[] stringArray0 = new String[0];
      NewMenu newMenu0 = new NewMenu(stringArray0);
      // Undeclared exception!
      try { 
        newMenu0.setHandler((-5259), (NewMenu.Handler) null);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      NewMenu newMenu0 = new NewMenu();
      // Undeclared exception!
      try { 
        newMenu0.run();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.example.Main.NewMenu", e);
      }
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      String[] stringArray0 = new String[5];
      NewMenu newMenu0 = new NewMenu(stringArray0);
      newMenu0.setHandler(4, (NewMenu.Handler) null);
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      String[] stringArray0 = new String[2];
      NewMenu newMenu0 = new NewMenu(stringArray0);
      NewMenu.PreCondition newMenu_PreCondition0 = mock(NewMenu.PreCondition.class, new ViolatedAssumptionAnswer());
      // Undeclared exception!
      try { 
        newMenu0.setPreCondition((-5476), newMenu_PreCondition0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      NewMenu newMenu0 = null;
      try {
        newMenu0 = new NewMenu((String[]) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.Objects", e);
      }
  }
}
